### ISSUE TITLE
Sửa lỗi

### ISSUE THREAD

**Issue by richieieie** [LMKhoa123/KitStemHub-FE-Customer#62]
- Trong profile chưa sửa, chọn: Thông tin tài khoản và địa chỉ giao hàng:
 + Nếu chọn thông tin tài khoản thì hiển thị đầy đủ
 + Giữ địa chỉ giao hàng thì trên thông tin tài khoản không nên có địa chỉ giao hàng
- Check out page chưa push code nên chưa check được
- Homepage filter vừa chọn category và search name ra không đúng:
 + Vd: Chọn arduino xong search thử chữ "s" thì nó hiện ra luôn kits của LEGO

**Comment by LMKhoa123** [comment]
Fixed: Homepage filter vừa chọn category và search name ra không đúng

**Comment by QzUzAzN** [comment]
đã sửa : 
Trong profile chưa sửa, chọn: Thông tin tài khoản và địa chỉ giao hàng:
Nếu chọn thông tin tài khoản thì hiển thị đầy đủ
Giữ địa chỉ giao hàng thì trên thông tin tài khoản không nên có địa chỉ giao hàng
Check out page chưa push code nên chưa check được
